FROM python:3.7-slim
RUN apt update && apt install -y \
    python3-dev \
    python3-pip \
    youtube-dl \
    curl
COPY ./requirements.txt /usr/local/src/celery_testing/
RUN pip3 install -r /usr/local/src/celery_testing/requirements.txt
RUN pip3 install --upgrade youtube-dl
COPY . /usr/local/src/celery_testing/
WORKDIR /usr/local/src/celery_testing/